
import React from 'react';
import { Helmet } from 'react-helmet';
import { motion } from 'framer-motion';
import Header from '@/components/Header.jsx';
import Footer from '@/components/Footer.jsx';

const TermsOfServicePage = () => {
  return (
    <>
      <Helmet>
        <title>{`Terms of Service - FoundersROI`}</title>
        <meta name="description" content="Terms of Service for FoundersROI. Please read carefully before using our tools." />
      </Helmet>

      <div className="min-h-screen bg-background">
        <Header />

        <main className="section-padding">
          <div className="container-custom max-w-3xl">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              <h1 className="mb-4 text-3xl sm:text-4xl md:text-5xl">Terms of Service</h1>
              <p className="text-muted-foreground mb-8 sm:mb-12">Effective Date: May 9, 2026</p>

              <div className="prose prose-invert prose-p:text-muted-foreground prose-headings:text-foreground max-w-none space-y-8">
                <section>
                  <h2 className="text-2xl font-semibold mb-4">1. Disclaimer</h2>
                  <p>
                    The FoundersROI calculator provides estimates based on self-reported inputs and general industry benchmarks. The results, reports, and recommendations generated by our tools are for informational and planning purposes only. They do <strong>not</strong> constitute financial, legal, or professional investment advice. Your actual return on investment may vary based on implementation and market factors.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-semibold mb-4">2. Delivery</h2>
                  <p>
                    For users who purchase our Audit or Sprint services, we commit to delivering the initial customized report and materials within 24 hours of successful payment confirmation and data submission. The report will be sent to the email address provided during checkout.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-semibold mb-4">3. User Responsibility</h2>
                  <p>
                    You are solely responsible for the accuracy of the inputs you provide to the calculator. FoundersROI is not liable for business decisions made based on inaccurate data entry or misunderstandings of the tool's estimations.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-semibold mb-4">4. Service Updates</h2>
                  <p>
                    We reserve the right to update, modify, or discontinue any aspect of the FoundersROI service, including calculator algorithms, pricing, and these terms, at any time without prior notice. Continued use of the service constitutes acceptance of any updated terms.
                  </p>
                </section>

                <section>
                  <h2 className="text-2xl font-semibold mb-4">5. Governing Law</h2>
                  <p>
                    These Terms of Service and your use of FoundersROI shall be governed by and construed in accordance with standard business laws.
                  </p>
                </section>
              </div>
            </motion.div>
          </div>
        </main>

        <Footer />
      </div>
    </>
  );
};

export default TermsOfServicePage;
